// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbBAKMSQrG3fRmloJsGa5gI4K4sgbykE',
    appId: '1:722283834692:web:c496a735c2f0b596d4fb11',
    messagingSenderId: '722283834692',
    projectId: 'storeapp-a0f0a',
    authDomain: 'storeapp-a0f0a.firebaseapp.com',
    storageBucket: 'storeapp-a0f0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsphaFqrthd1DkbDO7r6B6MeBp964MPdw',
    appId: '1:722283834692:android:29527651dcc4a75ed4fb11',
    messagingSenderId: '722283834692',
    projectId: 'storeapp-a0f0a',
    storageBucket: 'storeapp-a0f0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmcHGhaBRewkiBNQK3DnUDw-yEzM6sv9g',
    appId: '1:722283834692:ios:0f61ef241c44695fd4fb11',
    messagingSenderId: '722283834692',
    projectId: 'storeapp-a0f0a',
    storageBucket: 'storeapp-a0f0a.appspot.com',
    iosClientId: '722283834692-p48vbhndjka8636u2agjvlo4cr7s4v59.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanday14danday15sekolahbeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmcHGhaBRewkiBNQK3DnUDw-yEzM6sv9g',
    appId: '1:722283834692:ios:0f61ef241c44695fd4fb11',
    messagingSenderId: '722283834692',
    projectId: 'storeapp-a0f0a',
    storageBucket: 'storeapp-a0f0a.appspot.com',
    iosClientId: '722283834692-p48vbhndjka8636u2agjvlo4cr7s4v59.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanday14danday15sekolahbeta',
  );
}
